### ISSUE TITLE
*"该日期数据记录不存在"

### ISSUE THREAD

**Issue by Ca1Cai** [benx1n/HikariBot#1]
![image](https://user-images.githubusercontent.com/55339163/172541643-57c0127a-86a7-456f-9673-71adef25ce48.png)

**Comment by Ca1Cai** [comment]
others' are fine

**Comment by benx1n** [comment]
您可以发送wws help查看recent对应说明
>recent查不到的问题：
recent是基于你绑定账号那天起,服务器会在每日凌晨开始记录你的战绩数据
所以理论上是第一天绑定第二天才可以查询当日的数据.
1.绑定了查不到可能是服务器那几天宕机了导致没数据，建议看看公告近期是否有宕机
2.如果你是以前绑定的现在请重新绑定一次，之前的记录清理了
3.recent会定期清理掉隐藏战绩的账号、一个月没有玩的账号
