### ISSUE TITLE
与其他插件共同使用时，其他插件失效

### ISSUE THREAD

**Issue by Ra1n-qwq** [benx1n/HikariBot#11]
如与nonebot_plugin_memes、nonebot_plugin_petpet使用时，消息无法传递到后续插件中

**Comment by benx1n** [comment]
已修复，请更新至v0.3.3

**Comment by Ra1n-qwq** [comment]
已更新至最新版，但好像并没有解决。用nb-cli和pip进行更新，均未能解决。
![image](https://user-images.githubusercontent.com/70008390/179329795-b19e4c45-ba43-4a67-88c9-e29a7e566218.png)
![image](https://user-images.githubusercontent.com/70008390/179329846-2d1dd549-c96c-4a7b-af9e-7847fb63247a.png)

**Comment by benx1n** [comment]
请尝试将依赖中__init__.py中第38行修改为
`bot_listen = on_message(priority=5,block=False)`
关于依赖包位置你可以通过pip uninstall hikari-bot获得

**Comment by Ra1n-qwq** [comment]
第39行也需要进行修改：
bot_checkversion = on_command("wws 检查更新",priority=5,block=False)

**Comment by benx1n** [comment]
已发布0.3.3.1
