### ISSUE TITLE
Nonebot2 无法正常加载

### ISSUE THREAD

**Issue by bcbs-352** [benx1n/HikariBot#15]
![UW2X_`WE4~7CD 24`A5EOF8](https://user-images.githubusercontent.com/74083955/184483637-3f9f0321-3a3f-4fa3-9e77-c946027e759d.png)
ubuntu 20.04，nonebot2是最新的，.env.dev也配置了，其他插件是能正常加载

**Comment by benx1n** [comment]
https://github.com/benx1n/HikariBot#failed-to-import-nonebot_plugin_guild_patch
