### ISSUE TITLE
【报错】自动更新失败

### ISSUE THREAD

**Issue by Agnes4m** [benx1n/HikariBot#25]
指令`wws 更新Hikari`，由于启动是python3而不是python，导致的错误
没截全）
```
xt', data={'text': '正在更新Hikari，完成后将自动重启，如果没有回复您已上线的消息，请登录服务器查看'})]}
sh: 1: python: not found
sh: 1: python: not found
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.9/multiprocessing/spawn.py", line 115, in spawn_main
    parent_sentinel = os.dup(pipe_handle)
OSError: [Errno 9] Bad file descriptor
```

**Comment by benx1n** [comment]
是完整clone仓库部署的吗？
之前测试过linux的一键脚本，应该是支持指令更新的，也可以使用一键脚本自带的更新方式：
推荐linux使用一键脚本搭建，更新会比较简单，应该也是支持目前的：

> 3. 登录服务器运行 systemctl restart qqbot 命令重启机器人服务。
或者直接在云服务商的面板上重启整个系统来重启qq机器人。机器人开机自启
   （添加qq账号并扫码等后需要重启bot才能生效）
PS：机器人每次启动前会先更新hikari-bot
This message saved in /root/HikariBot/help.txt.

**Comment by benx1n** [comment]
已与0.3.5.4修复
