### ISSUE TITLE
群晖Docker部署运行卡住无法继续

### ISSUE THREAD

**Issue by YsWGYY** [benx1n/HikariBot#47]
从Windows上运行了一下机器人正常使用，想部署到群晖上

通过命令启动镜像 token和qq都配置无误 
docker run -d -p 12345:8080 12hydrogen/hikari-bot:latest -t token -i qqid
运行容器后卡到running nonebot  无法继续下去 
04-09 14:56:15 [SUCCESS] nonebot | Running NoneBot...

通过端口进入网页提示 {"detail":"Not Found"}

**Comment by benx1n** [comment]
网页的路径对了吗，后续需要加上/go-cqhttp/

**Comment by YsWGYY** [comment]
是少了后缀  加上就好了

不过我从istoreOS openwrt上下载docker镜像报这个错误是什么问题
error creating overlay mount to /ext_overlay/docker/overlay2/ca109ea6c9fe0efbdab4fd8b974fc973fba7c3051e98c8efbb23f052256a794a/merged: too many levels of symbolic links

**Comment by YsWGYY** [comment]
![1681168987452](https://user-images.githubusercontent.com/120236649/231017589-89035960-e416-46e4-a3c3-4d0bdeb37c90.png)

**Comment by 12hydrogen** [comment]
@YsWGYY 这个有可能是因为Docker的问题。这一问题同样出现在很多其他镜像上，共同特点似乎是有一个较大的只读层。按照Docker那里的Issue来看，完全删除Docker及其附属文件，然后再次安装Docker应该可以解决这个问题。
