### ISSUE TITLE
你的linux的一键包该更新了

### ISSUE THREAD

**Issue by FrostLeafKEE** [benx1n/HikariBot#48]

**Comment by benx1n** [comment]
Linux的脚本目前有什么问题吗

**Comment by FrostLeafKEE** [comment]
go-cqhttp版本过低，应该是这样

**Comment by benx1n** [comment]
用的是这个仓库啊，怎么会过低呢 [mnixry/nonebot-plugin-gocqhttp](https://github.com/mnixry/nonebot-plugin-gocqhttp)
