### ISSUE TITLE
请更新env配置项列表

### ISSUE THREAD

**Issue by 1717tian** [benx1n/HikariBot#55]
如题
当插件配置新版本时发现缺配置项
从一件包的env找着了
（emm太长时间没发言被从群里撅出去了 悲）

**Comment by 1717tian** [comment]
htmlrender_browser

**Comment by benx1n** [comment]
更新方法里写了，更新后对比prod-template中新增的配置添加到env.prod中
如果使用的是一键包的自动更新方法，会自动下载最新的env文件，在env.prod中找不到的配置项会去env中找
你如果通过其他方式更新的，可以手动覆盖最新的env文件

**Comment by benx1n** [comment]
目前没有其他比较好的自动更新env.prod中配置的方法，后续或许会搞一个可视化控制台？不用nonebot2自带的这套环境配置了
