### ISSUE TITLE
缺少图标

### ISSUE THREAD

**Issue by 1717tian** [benx1n/HikariBot#62]
emmmmm
![7707e7e644697150208442950faf7fb3](https://github.com/user-attachments/assets/8555de49-bd8c-46b6-8544-83f752ddc769)
无报错 缺少个别船图标

**Comment by benx1n** [comment]
@JustOneSummer 这个似乎是wg那边没资源？

**Comment by JustOneSummer** [comment]
已经修复了 @1717tian

**Comment by 1717tian** [comment]
辛苦力
